/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AnalisisIaSchema extends BaseModel {
  static $columns = ['fechaActualizacion', 'fechaRegistro', 'idAnalisis', 'idEstado', 'idImagen', 'idNivelRoya', 'porcentajeConfianza', 'resultado'] as const
  $columns = AnalisisIaSchema.$columns
  @column.dateTime()
  declare fechaActualizacion: DateTime | null
  @column.dateTime()
  declare fechaRegistro: DateTime | null
  @column({ isPrimary: true })
  declare idAnalisis: number
  @column()
  declare idEstado: number | null
  @column()
  declare idImagen: number | null
  @column()
  declare idNivelRoya: number | null
  @column()
  declare porcentajeConfianza: string | null
  @column()
  declare resultado: string | null
}

export class AplicacionesTratamientoSchema extends BaseModel {
  static $columns = ['fechaAplicacion', 'fechaRegistro', 'idAplicacion', 'idTratamiento', 'idUsuario', 'observacion'] as const
  $columns = AplicacionesTratamientoSchema.$columns
  @column.date()
  declare fechaAplicacion: DateTime
  @column.dateTime()
  declare fechaRegistro: DateTime
  @column({ isPrimary: true })
  declare idAplicacion: number
  @column()
  declare idTratamiento: number
  @column()
  declare idUsuario: number | null
  @column()
  declare observacion: string | null
}

export class AsignacionesExpertoSchema extends BaseModel {
  static $columns = ['fechaActualizacion', 'fechaAsignada', 'fechaRegistro', 'idAsignacion', 'idExperto', 'idFinca'] as const
  $columns = AsignacionesExpertoSchema.$columns
  @column.dateTime()
  declare fechaActualizacion: DateTime
  @column.date()
  declare fechaAsignada: DateTime
  @column.dateTime()
  declare fechaRegistro: DateTime
  @column({ isPrimary: true })
  declare idAsignacion: number
  @column()
  declare idExperto: number
  @column()
  declare idFinca: number
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CatEstadosAnalisiSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idEstado', 'nombreEstado', 'updatedAt'] as const
  $columns = CatEstadosAnalisiSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idEstado: number
  @column()
  declare nombreEstado: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatEstadosCultivoSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idEstado', 'nombreEstado', 'updatedAt'] as const
  $columns = CatEstadosCultivoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idEstado: number
  @column()
  declare nombreEstado: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatNivelesRoyaSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idNivel', 'nombreNivel', 'updatedAt'] as const
  $columns = CatNivelesRoyaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idNivel: number
  @column()
  declare nombreNivel: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatPrioridadeSchema extends BaseModel {
  static $columns = ['createdAt', 'idPrioridad', 'nivelOrden', 'nombre', 'updatedAt'] as const
  $columns = CatPrioridadeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare idPrioridad: number
  @column()
  declare nivelOrden: number | null
  @column()
  declare nombre: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idRol', 'nombreRol', 'updatedAt'] as const
  $columns = CatRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idRol: number
  @column()
  declare nombreRol: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatTiposInsumoSchema extends BaseModel {
  static $columns = ['fechaActualizacion', 'fechaRegistro', 'idTipoInsumo', 'nombre'] as const
  $columns = CatTiposInsumoSchema.$columns
  @column.dateTime()
  declare fechaActualizacion: DateTime | null
  @column.dateTime()
  declare fechaRegistro: DateTime | null
  @column({ isPrimary: true })
  declare idTipoInsumo: number
  @column()
  declare nombre: string
}

export class CatTiposRecomendacionSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idTipo', 'nombreTipo', 'updatedAt'] as const
  $columns = CatTiposRecomendacionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idTipo: number
  @column()
  declare nombreTipo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CatTiposTratamientoSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'idTipo', 'nombreTipo', 'updatedAt'] as const
  $columns = CatTiposTratamientoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare idTipo: number
  @column()
  declare nombreTipo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CultivoSchema extends BaseModel {
  static $columns = ['createdAt', 'fotoUrl', 'idCultivo', 'idEstado', 'idFinca', 'nombreCultivo', 'numeroArboles', 'tipoCultivo', 'updatedAt', 'variedadCafe'] as const
  $columns = CultivoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare fotoUrl: string | null
  @column({ isPrimary: true })
  declare idCultivo: number
  @column()
  declare idEstado: number | null
  @column()
  declare idFinca: number | null
  @column()
  declare nombreCultivo: string
  @column()
  declare numeroArboles: number | null
  @column()
  declare tipoCultivo: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare variedadCafe: string | null
}

export class FincaSchema extends BaseModel {
  static $columns = ['activo', 'altitudMsnm', 'areaHectareas', 'departamento', 'fechaActualizacion', 'fechaRegistro', 'fotoUrl', 'idFinca', 'idUsuario', 'latitud', 'longitud', 'municipio', 'nombreFinca'] as const
  $columns = FincaSchema.$columns
  @column()
  declare activo: boolean | null
  @column()
  declare altitudMsnm: string | null
  @column()
  declare areaHectareas: string | null
  @column()
  declare departamento: string
  @column.dateTime()
  declare fechaActualizacion: DateTime
  @column.dateTime()
  declare fechaRegistro: DateTime
  @column()
  declare fotoUrl: string | null
  @column({ isPrimary: true })
  declare idFinca: number
  @column()
  declare idUsuario: number | null
  @column()
  declare latitud: string | null
  @column()
  declare longitud: string | null
  @column()
  declare municipio: string
  @column()
  declare nombreFinca: string
}

export class ImageneSchema extends BaseModel {
  static $columns = ['fechaActualizacion', 'fechaRegistro', 'idImagen', 'idMonitoreo', 'rutaImagen'] as const
  $columns = ImageneSchema.$columns
  @column.dateTime()
  declare fechaActualizacion: DateTime | null
  @column.dateTime()
  declare fechaRegistro: DateTime | null
  @column({ isPrimary: true })
  declare idImagen: number
  @column()
  declare idMonitoreo: number | null
  @column()
  declare rutaImagen: string
}

export class InsumoSchema extends BaseModel {
  static $columns = ['descripcion', 'fechaActualizacion', 'fechaRegistro', 'idInsumo', 'idTipoInsumo', 'nombre'] as const
  $columns = InsumoSchema.$columns
  @column()
  declare descripcion: string | null
  @column.dateTime()
  declare fechaActualizacion: DateTime | null
  @column.dateTime()
  declare fechaRegistro: DateTime | null
  @column({ isPrimary: true })
  declare idInsumo: number
  @column()
  declare idTipoInsumo: number | null
  @column()
  declare nombre: string
}

export class MonitoreoSchema extends BaseModel {
  static $columns = ['fechaActualizacion', 'fechaMonitoreo', 'fechaRegistro', 'idCultivo', 'idMonitoreo', 'idUsuario', 'observaciones'] as const
  $columns = MonitoreoSchema.$columns
  @column.dateTime()
  declare fechaActualizacion: DateTime
  @column.dateTime()
  declare fechaMonitoreo: DateTime
  @column.dateTime()
  declare fechaRegistro: DateTime
  @column()
  declare idCultivo: number | null
  @column({ isPrimary: true })
  declare idMonitoreo: number
  @column()
  declare idUsuario: number | null
  @column()
  declare observaciones: string | null
}

export class NotificacioneSchema extends BaseModel {
  static $columns = ['fechaRegistro', 'idNotificacion', 'idReferencia', 'idUsuario', 'leida', 'mensaje', 'tablaReferencia', 'tipo', 'titulo'] as const
  $columns = NotificacioneSchema.$columns
  @column.dateTime()
  declare fechaRegistro: DateTime | null
  @column({ isPrimary: true })
  declare idNotificacion: number
  @column()
  declare idReferencia: number | null
  @column()
  declare idUsuario: number
  @column()
  declare leida: boolean | null
  @column()
  declare mensaje: string
  @column()
  declare tablaReferencia: string | null
  @column()
  declare tipo: string
  @column()
  declare titulo: string
}

export class RecomendacioneSchema extends BaseModel {
  static $columns = ['descripcion', 'fechaActualizacion', 'fechaLimite', 'fechaRegistro', 'idExpertoEmisor', 'idMonitoreo', 'idPrioridad', 'idRecomendacion', 'idTipo', 'idTratamiento'] as const
  $columns = RecomendacioneSchema.$columns
  @column()
  declare descripcion: string | null
  @column.dateTime()
  declare fechaActualizacion: DateTime
  @column.date()
  declare fechaLimite: DateTime | null
  @column.dateTime()
  declare fechaRegistro: DateTime
  @column()
  declare idExpertoEmisor: number | null
  @column()
  declare idMonitoreo: number | null
  @column()
  declare idPrioridad: number | null
  @column({ isPrimary: true })
  declare idRecomendacion: number
  @column()
  declare idTipo: number | null
  @column()
  declare idTratamiento: number | null
}

export class TratamientoSchema extends BaseModel {
  static $columns = ['descripcion', 'dosis', 'fechaActualizacion', 'fechaRegistro', 'frecuencia', 'idInsumo', 'idTipoTratamiento', 'idTratamiento', 'nombre', 'observaciones'] as const
  $columns = TratamientoSchema.$columns
  @column()
  declare descripcion: string | null
  @column()
  declare dosis: string | null
  @column.dateTime()
  declare fechaActualizacion: DateTime
  @column.dateTime()
  declare fechaRegistro: DateTime
  @column()
  declare frecuencia: string | null
  @column()
  declare idInsumo: number | null
  @column()
  declare idTipoTratamiento: number | null
  @column({ isPrimary: true })
  declare idTratamiento: number
  @column()
  declare nombre: string
  @column()
  declare observaciones: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UsuarioSchema extends BaseModel {
  static $columns = ['activo', 'apellido', 'cedula', 'correo', 'fechaActualizacion', 'fechaRegistro', 'fotoPerfil', 'genero', 'idRol', 'idUsuario', 'nombre', 'observaciones', 'passwordHash', 'resetToken', 'resetTokenExpires', 'telefono'] as const
  $columns = UsuarioSchema.$columns
  @column()
  declare activo: boolean | null
  @column()
  declare apellido: string
  @column()
  declare cedula: string | null
  @column()
  declare correo: string
  @column.dateTime()
  declare fechaActualizacion: DateTime
  @column.dateTime()
  declare fechaRegistro: DateTime
  @column()
  declare fotoPerfil: string | null
  @column()
  declare genero: string | null
  @column()
  declare idRol: number | null
  @column({ isPrimary: true })
  declare idUsuario: number
  @column()
  declare nombre: string
  @column()
  declare observaciones: string | null
  @column()
  declare passwordHash: string
  @column()
  declare resetToken: string | null
  @column.dateTime()
  declare resetTokenExpires: DateTime | null
  @column()
  declare telefono: string | null
}
