/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.login': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.register': {
    methods: ["POST"],
    pattern: '/register',
    tokens: [{"old":"/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.register']['types'],
  },
  'auth.recuperar_password': {
    methods: ["POST"],
    pattern: '/recuperar-password',
    tokens: [{"old":"/recuperar-password","type":0,"val":"recuperar-password","end":""}],
    types: placeholder as Registry['auth.recuperar_password']['types'],
  },
  'auth.verificar_token': {
    methods: ["POST"],
    pattern: '/verificar-token',
    tokens: [{"old":"/verificar-token","type":0,"val":"verificar-token","end":""}],
    types: placeholder as Registry['auth.verificar_token']['types'],
  },
  'auth.restablecer_password': {
    methods: ["POST"],
    pattern: '/restablecer-password',
    tokens: [{"old":"/restablecer-password","type":0,"val":"restablecer-password","end":""}],
    types: placeholder as Registry['auth.restablecer_password']['types'],
  },
  'mi_perfil.show': {
    methods: ["GET","HEAD"],
    pattern: '/mi-perfil',
    tokens: [{"old":"/mi-perfil","type":0,"val":"mi-perfil","end":""}],
    types: placeholder as Registry['mi_perfil.show']['types'],
  },
  'mi_perfil.update': {
    methods: ["PUT"],
    pattern: '/mi-perfil',
    tokens: [{"old":"/mi-perfil","type":0,"val":"mi-perfil","end":""}],
    types: placeholder as Registry['mi_perfil.update']['types'],
  },
  'mi_perfil.cambiar_password': {
    methods: ["POST"],
    pattern: '/mi-perfil/cambiar-password',
    tokens: [{"old":"/mi-perfil/cambiar-password","type":0,"val":"mi-perfil","end":""},{"old":"/mi-perfil/cambiar-password","type":0,"val":"cambiar-password","end":""}],
    types: placeholder as Registry['mi_perfil.cambiar_password']['types'],
  },
  'cat_roles.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_roles',
    tokens: [{"old":"/cat_roles","type":0,"val":"cat_roles","end":""}],
    types: placeholder as Registry['cat_roles.index']['types'],
  },
  'cat_roles.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_roles/:id',
    tokens: [{"old":"/cat_roles/:id","type":0,"val":"cat_roles","end":""},{"old":"/cat_roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_roles.show']['types'],
  },
  'cat_tipos_tratamientos.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_tipos_tratamientos',
    tokens: [{"old":"/cat_tipos_tratamientos","type":0,"val":"cat_tipos_tratamientos","end":""}],
    types: placeholder as Registry['cat_tipos_tratamientos.index']['types'],
  },
  'cat_tipos_tratamientos.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_tipos_tratamientos/:id',
    tokens: [{"old":"/cat_tipos_tratamientos/:id","type":0,"val":"cat_tipos_tratamientos","end":""},{"old":"/cat_tipos_tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_tratamientos.show']['types'],
  },
  'cat_niveles_royas.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_niveles_roya',
    tokens: [{"old":"/cat_niveles_roya","type":0,"val":"cat_niveles_roya","end":""}],
    types: placeholder as Registry['cat_niveles_royas.index']['types'],
  },
  'cat_niveles_royas.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_niveles_roya/:id',
    tokens: [{"old":"/cat_niveles_roya/:id","type":0,"val":"cat_niveles_roya","end":""},{"old":"/cat_niveles_roya/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_niveles_royas.show']['types'],
  },
  'cat_prioridades.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_prioridades',
    tokens: [{"old":"/cat_prioridades","type":0,"val":"cat_prioridades","end":""}],
    types: placeholder as Registry['cat_prioridades.index']['types'],
  },
  'cat_prioridades.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_prioridades/:id',
    tokens: [{"old":"/cat_prioridades/:id","type":0,"val":"cat_prioridades","end":""},{"old":"/cat_prioridades/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_prioridades.show']['types'],
  },
  'cat_tipos_recomendaciones.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_tipos_recomendaciones',
    tokens: [{"old":"/cat_tipos_recomendaciones","type":0,"val":"cat_tipos_recomendaciones","end":""}],
    types: placeholder as Registry['cat_tipos_recomendaciones.index']['types'],
  },
  'cat_tipos_recomendaciones.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_tipos_recomendaciones/:id',
    tokens: [{"old":"/cat_tipos_recomendaciones/:id","type":0,"val":"cat_tipos_recomendaciones","end":""},{"old":"/cat_tipos_recomendaciones/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_recomendaciones.show']['types'],
  },
  'cat_estados_analisis.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_estados_analisis',
    tokens: [{"old":"/cat_estados_analisis","type":0,"val":"cat_estados_analisis","end":""}],
    types: placeholder as Registry['cat_estados_analisis.index']['types'],
  },
  'cat_estados_analisis.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_estados_analisis/:id',
    tokens: [{"old":"/cat_estados_analisis/:id","type":0,"val":"cat_estados_analisis","end":""},{"old":"/cat_estados_analisis/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_estados_analisis.show']['types'],
  },
  'cat_estados_cultivos.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_estados_cultivo',
    tokens: [{"old":"/cat_estados_cultivo","type":0,"val":"cat_estados_cultivo","end":""}],
    types: placeholder as Registry['cat_estados_cultivos.index']['types'],
  },
  'cat_estados_cultivos.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_estados_cultivo/:id',
    tokens: [{"old":"/cat_estados_cultivo/:id","type":0,"val":"cat_estados_cultivo","end":""},{"old":"/cat_estados_cultivo/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_estados_cultivos.show']['types'],
  },
  'categorias.index': {
    methods: ["GET","HEAD"],
    pattern: '/categorias',
    tokens: [{"old":"/categorias","type":0,"val":"categorias","end":""}],
    types: placeholder as Registry['categorias.index']['types'],
  },
  'categorias.show': {
    methods: ["GET","HEAD"],
    pattern: '/categorias/:id',
    tokens: [{"old":"/categorias/:id","type":0,"val":"categorias","end":""},{"old":"/categorias/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categorias.show']['types'],
  },
  'cat_tipos_insumos.index': {
    methods: ["GET","HEAD"],
    pattern: '/cat_tipos_insumos',
    tokens: [{"old":"/cat_tipos_insumos","type":0,"val":"cat_tipos_insumos","end":""}],
    types: placeholder as Registry['cat_tipos_insumos.index']['types'],
  },
  'cat_tipos_insumos.show': {
    methods: ["GET","HEAD"],
    pattern: '/cat_tipos_insumos/:id',
    tokens: [{"old":"/cat_tipos_insumos/:id","type":0,"val":"cat_tipos_insumos","end":""},{"old":"/cat_tipos_insumos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_insumos.show']['types'],
  },
  'insumos.index': {
    methods: ["GET","HEAD"],
    pattern: '/insumos',
    tokens: [{"old":"/insumos","type":0,"val":"insumos","end":""}],
    types: placeholder as Registry['insumos.index']['types'],
  },
  'insumos.show': {
    methods: ["GET","HEAD"],
    pattern: '/insumos/:id',
    tokens: [{"old":"/insumos/:id","type":0,"val":"insumos","end":""},{"old":"/insumos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['insumos.show']['types'],
  },
  'dashboard.index': {
    methods: ["GET","HEAD"],
    pattern: '/dashboard',
    tokens: [{"old":"/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard.index']['types'],
  },
  'usuarios.index': {
    methods: ["GET","HEAD"],
    pattern: '/usuarios',
    tokens: [{"old":"/usuarios","type":0,"val":"usuarios","end":""}],
    types: placeholder as Registry['usuarios.index']['types'],
  },
  'usuarios.store': {
    methods: ["POST"],
    pattern: '/usuarios',
    tokens: [{"old":"/usuarios","type":0,"val":"usuarios","end":""}],
    types: placeholder as Registry['usuarios.store']['types'],
  },
  'usuarios.show': {
    methods: ["GET","HEAD"],
    pattern: '/usuarios/:id',
    tokens: [{"old":"/usuarios/:id","type":0,"val":"usuarios","end":""},{"old":"/usuarios/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['usuarios.show']['types'],
  },
  'usuarios.update': {
    methods: ["PUT"],
    pattern: '/usuarios/:id',
    tokens: [{"old":"/usuarios/:id","type":0,"val":"usuarios","end":""},{"old":"/usuarios/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['usuarios.update']['types'],
  },
  'usuarios.destroy': {
    methods: ["DELETE"],
    pattern: '/usuarios/:id',
    tokens: [{"old":"/usuarios/:id","type":0,"val":"usuarios","end":""},{"old":"/usuarios/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['usuarios.destroy']['types'],
  },
  'admin.index': {
    methods: ["GET","HEAD"],
    pattern: '/admins',
    tokens: [{"old":"/admins","type":0,"val":"admins","end":""}],
    types: placeholder as Registry['admin.index']['types'],
  },
  'admin.store': {
    methods: ["POST"],
    pattern: '/admins',
    tokens: [{"old":"/admins","type":0,"val":"admins","end":""}],
    types: placeholder as Registry['admin.store']['types'],
  },
  'admin.show': {
    methods: ["GET","HEAD"],
    pattern: '/admins/:id',
    tokens: [{"old":"/admins/:id","type":0,"val":"admins","end":""},{"old":"/admins/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.show']['types'],
  },
  'admin.update': {
    methods: ["PUT"],
    pattern: '/admins/:id',
    tokens: [{"old":"/admins/:id","type":0,"val":"admins","end":""},{"old":"/admins/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.update']['types'],
  },
  'admin.destroy': {
    methods: ["DELETE"],
    pattern: '/admins/:id',
    tokens: [{"old":"/admins/:id","type":0,"val":"admins","end":""},{"old":"/admins/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.destroy']['types'],
  },
  'expertos.index': {
    methods: ["GET","HEAD"],
    pattern: '/expertos',
    tokens: [{"old":"/expertos","type":0,"val":"expertos","end":""}],
    types: placeholder as Registry['expertos.index']['types'],
  },
  'expertos.store': {
    methods: ["POST"],
    pattern: '/expertos',
    tokens: [{"old":"/expertos","type":0,"val":"expertos","end":""}],
    types: placeholder as Registry['expertos.store']['types'],
  },
  'expertos.show': {
    methods: ["GET","HEAD"],
    pattern: '/expertos/:id',
    tokens: [{"old":"/expertos/:id","type":0,"val":"expertos","end":""},{"old":"/expertos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['expertos.show']['types'],
  },
  'expertos.update': {
    methods: ["PUT"],
    pattern: '/expertos/:id',
    tokens: [{"old":"/expertos/:id","type":0,"val":"expertos","end":""},{"old":"/expertos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['expertos.update']['types'],
  },
  'expertos.destroy': {
    methods: ["DELETE"],
    pattern: '/expertos/:id',
    tokens: [{"old":"/expertos/:id","type":0,"val":"expertos","end":""},{"old":"/expertos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['expertos.destroy']['types'],
  },
  'asignaciones_expertos.store': {
    methods: ["POST"],
    pattern: '/asignaciones_expertos',
    tokens: [{"old":"/asignaciones_expertos","type":0,"val":"asignaciones_expertos","end":""}],
    types: placeholder as Registry['asignaciones_expertos.store']['types'],
  },
  'asignaciones_expertos.update': {
    methods: ["PUT"],
    pattern: '/asignaciones_expertos/:id',
    tokens: [{"old":"/asignaciones_expertos/:id","type":0,"val":"asignaciones_expertos","end":""},{"old":"/asignaciones_expertos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['asignaciones_expertos.update']['types'],
  },
  'asignaciones_expertos.destroy': {
    methods: ["DELETE"],
    pattern: '/asignaciones_expertos/:id',
    tokens: [{"old":"/asignaciones_expertos/:id","type":0,"val":"asignaciones_expertos","end":""},{"old":"/asignaciones_expertos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['asignaciones_expertos.destroy']['types'],
  },
  'cat_roles.store': {
    methods: ["POST"],
    pattern: '/cat_roles',
    tokens: [{"old":"/cat_roles","type":0,"val":"cat_roles","end":""}],
    types: placeholder as Registry['cat_roles.store']['types'],
  },
  'cat_roles.update': {
    methods: ["PUT"],
    pattern: '/cat_roles/:id',
    tokens: [{"old":"/cat_roles/:id","type":0,"val":"cat_roles","end":""},{"old":"/cat_roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_roles.update']['types'],
  },
  'cat_roles.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_roles/:id',
    tokens: [{"old":"/cat_roles/:id","type":0,"val":"cat_roles","end":""},{"old":"/cat_roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_roles.destroy']['types'],
  },
  'cat_tipos_tratamientos.store': {
    methods: ["POST"],
    pattern: '/cat_tipos_tratamiento',
    tokens: [{"old":"/cat_tipos_tratamiento","type":0,"val":"cat_tipos_tratamiento","end":""}],
    types: placeholder as Registry['cat_tipos_tratamientos.store']['types'],
  },
  'cat_tipos_tratamientos.update': {
    methods: ["PUT"],
    pattern: '/cat_tipos_tratamiento/:id',
    tokens: [{"old":"/cat_tipos_tratamiento/:id","type":0,"val":"cat_tipos_tratamiento","end":""},{"old":"/cat_tipos_tratamiento/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_tratamientos.update']['types'],
  },
  'cat_tipos_tratamientos.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_tipos_tratamiento/:id',
    tokens: [{"old":"/cat_tipos_tratamiento/:id","type":0,"val":"cat_tipos_tratamiento","end":""},{"old":"/cat_tipos_tratamiento/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_tratamientos.destroy']['types'],
  },
  'cat_niveles_royas.store': {
    methods: ["POST"],
    pattern: '/cat_niveles_roya',
    tokens: [{"old":"/cat_niveles_roya","type":0,"val":"cat_niveles_roya","end":""}],
    types: placeholder as Registry['cat_niveles_royas.store']['types'],
  },
  'cat_niveles_royas.update': {
    methods: ["PUT"],
    pattern: '/cat_niveles_roya/:id',
    tokens: [{"old":"/cat_niveles_roya/:id","type":0,"val":"cat_niveles_roya","end":""},{"old":"/cat_niveles_roya/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_niveles_royas.update']['types'],
  },
  'cat_niveles_royas.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_niveles_roya/:id',
    tokens: [{"old":"/cat_niveles_roya/:id","type":0,"val":"cat_niveles_roya","end":""},{"old":"/cat_niveles_roya/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_niveles_royas.destroy']['types'],
  },
  'cat_prioridades.store': {
    methods: ["POST"],
    pattern: '/cat_prioridades',
    tokens: [{"old":"/cat_prioridades","type":0,"val":"cat_prioridades","end":""}],
    types: placeholder as Registry['cat_prioridades.store']['types'],
  },
  'cat_prioridades.update': {
    methods: ["PUT"],
    pattern: '/cat_prioridades/:id',
    tokens: [{"old":"/cat_prioridades/:id","type":0,"val":"cat_prioridades","end":""},{"old":"/cat_prioridades/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_prioridades.update']['types'],
  },
  'cat_prioridades.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_prioridades/:id',
    tokens: [{"old":"/cat_prioridades/:id","type":0,"val":"cat_prioridades","end":""},{"old":"/cat_prioridades/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_prioridades.destroy']['types'],
  },
  'cat_tipos_recomendaciones.store': {
    methods: ["POST"],
    pattern: '/cat_tipo_recomendacion',
    tokens: [{"old":"/cat_tipo_recomendacion","type":0,"val":"cat_tipo_recomendacion","end":""}],
    types: placeholder as Registry['cat_tipos_recomendaciones.store']['types'],
  },
  'cat_tipos_recomendaciones.update': {
    methods: ["PUT"],
    pattern: '/cat_tipo_recomendacion/:id',
    tokens: [{"old":"/cat_tipo_recomendacion/:id","type":0,"val":"cat_tipo_recomendacion","end":""},{"old":"/cat_tipo_recomendacion/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_recomendaciones.update']['types'],
  },
  'cat_tipos_recomendaciones.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_tipos_recomendacion/:id',
    tokens: [{"old":"/cat_tipos_recomendacion/:id","type":0,"val":"cat_tipos_recomendacion","end":""},{"old":"/cat_tipos_recomendacion/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_recomendaciones.destroy']['types'],
  },
  'cat_estados_analisis.store': {
    methods: ["POST"],
    pattern: '/cat_estados_analisis',
    tokens: [{"old":"/cat_estados_analisis","type":0,"val":"cat_estados_analisis","end":""}],
    types: placeholder as Registry['cat_estados_analisis.store']['types'],
  },
  'cat_estados_analisis.update': {
    methods: ["PUT"],
    pattern: '/cat_estados_analisis/:id',
    tokens: [{"old":"/cat_estados_analisis/:id","type":0,"val":"cat_estados_analisis","end":""},{"old":"/cat_estados_analisis/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_estados_analisis.update']['types'],
  },
  'cat_estados_analisis.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_estados_analisis/:id',
    tokens: [{"old":"/cat_estados_analisis/:id","type":0,"val":"cat_estados_analisis","end":""},{"old":"/cat_estados_analisis/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_estados_analisis.destroy']['types'],
  },
  'cat_estados_cultivos.store': {
    methods: ["POST"],
    pattern: '/cat_estados_cultivo',
    tokens: [{"old":"/cat_estados_cultivo","type":0,"val":"cat_estados_cultivo","end":""}],
    types: placeholder as Registry['cat_estados_cultivos.store']['types'],
  },
  'cat_estados_cultivos.update': {
    methods: ["PUT"],
    pattern: '/cat_estados_cultivo/:id',
    tokens: [{"old":"/cat_estados_cultivo/:id","type":0,"val":"cat_estados_cultivo","end":""},{"old":"/cat_estados_cultivo/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_estados_cultivos.update']['types'],
  },
  'cat_estados_cultivos.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_estados_cultivo/:id',
    tokens: [{"old":"/cat_estados_cultivo/:id","type":0,"val":"cat_estados_cultivo","end":""},{"old":"/cat_estados_cultivo/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_estados_cultivos.destroy']['types'],
  },
  'categorias.store': {
    methods: ["POST"],
    pattern: '/categorias',
    tokens: [{"old":"/categorias","type":0,"val":"categorias","end":""}],
    types: placeholder as Registry['categorias.store']['types'],
  },
  'categorias.update': {
    methods: ["PUT"],
    pattern: '/categorias/:id',
    tokens: [{"old":"/categorias/:id","type":0,"val":"categorias","end":""},{"old":"/categorias/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categorias.update']['types'],
  },
  'categorias.destroy': {
    methods: ["DELETE"],
    pattern: '/categorias/:id',
    tokens: [{"old":"/categorias/:id","type":0,"val":"categorias","end":""},{"old":"/categorias/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categorias.destroy']['types'],
  },
  'asignaciones_expertos.index': {
    methods: ["GET","HEAD"],
    pattern: '/asignaciones_expertos',
    tokens: [{"old":"/asignaciones_expertos","type":0,"val":"asignaciones_expertos","end":""}],
    types: placeholder as Registry['asignaciones_expertos.index']['types'],
  },
  'asignaciones_expertos.show': {
    methods: ["GET","HEAD"],
    pattern: '/asignaciones_expertos/:id',
    tokens: [{"old":"/asignaciones_expertos/:id","type":0,"val":"asignaciones_expertos","end":""},{"old":"/asignaciones_expertos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['asignaciones_expertos.show']['types'],
  },
  'cafeteros.index': {
    methods: ["GET","HEAD"],
    pattern: '/cafeteros',
    tokens: [{"old":"/cafeteros","type":0,"val":"cafeteros","end":""}],
    types: placeholder as Registry['cafeteros.index']['types'],
  },
  'cafeteros.show': {
    methods: ["GET","HEAD"],
    pattern: '/cafeteros/:id',
    tokens: [{"old":"/cafeteros/:id","type":0,"val":"cafeteros","end":""},{"old":"/cafeteros/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cafeteros.show']['types'],
  },
  'monitoreos.update': {
    methods: ["PUT"],
    pattern: '/monitoreos/:id',
    tokens: [{"old":"/monitoreos/:id","type":0,"val":"monitoreos","end":""},{"old":"/monitoreos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['monitoreos.update']['types'],
  },
  'analisis_ia.update': {
    methods: ["PUT"],
    pattern: '/analisis_ia/:id',
    tokens: [{"old":"/analisis_ia/:id","type":0,"val":"analisis_ia","end":""},{"old":"/analisis_ia/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['analisis_ia.update']['types'],
  },
  'analisis_ia.destroy': {
    methods: ["DELETE"],
    pattern: '/analisis_ia/:id',
    tokens: [{"old":"/analisis_ia/:id","type":0,"val":"analisis_ia","end":""},{"old":"/analisis_ia/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['analisis_ia.destroy']['types'],
  },
  'analisis_ia.predict': {
    methods: ["POST"],
    pattern: '/analisis_ia/predict',
    tokens: [{"old":"/analisis_ia/predict","type":0,"val":"analisis_ia","end":""},{"old":"/analisis_ia/predict","type":0,"val":"predict","end":""}],
    types: placeholder as Registry['analisis_ia.predict']['types'],
  },
  'recomendaciones.store': {
    methods: ["POST"],
    pattern: '/recomendaciones',
    tokens: [{"old":"/recomendaciones","type":0,"val":"recomendaciones","end":""}],
    types: placeholder as Registry['recomendaciones.store']['types'],
  },
  'recomendaciones.update': {
    methods: ["PUT"],
    pattern: '/recomendaciones/:id',
    tokens: [{"old":"/recomendaciones/:id","type":0,"val":"recomendaciones","end":""},{"old":"/recomendaciones/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['recomendaciones.update']['types'],
  },
  'recomendaciones.destroy': {
    methods: ["DELETE"],
    pattern: '/recomendaciones/:id',
    tokens: [{"old":"/recomendaciones/:id","type":0,"val":"recomendaciones","end":""},{"old":"/recomendaciones/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['recomendaciones.destroy']['types'],
  },
  'tratamientos.store': {
    methods: ["POST"],
    pattern: '/tratamientos',
    tokens: [{"old":"/tratamientos","type":0,"val":"tratamientos","end":""}],
    types: placeholder as Registry['tratamientos.store']['types'],
  },
  'tratamientos.update': {
    methods: ["PUT"],
    pattern: '/tratamientos/:id',
    tokens: [{"old":"/tratamientos/:id","type":0,"val":"tratamientos","end":""},{"old":"/tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tratamientos.update']['types'],
  },
  'tratamientos.destroy': {
    methods: ["DELETE"],
    pattern: '/tratamientos/:id',
    tokens: [{"old":"/tratamientos/:id","type":0,"val":"tratamientos","end":""},{"old":"/tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tratamientos.destroy']['types'],
  },
  'aplicaciones_tratamientos.store': {
    methods: ["POST"],
    pattern: '/aplicaciones_tratamientos',
    tokens: [{"old":"/aplicaciones_tratamientos","type":0,"val":"aplicaciones_tratamientos","end":""}],
    types: placeholder as Registry['aplicaciones_tratamientos.store']['types'],
  },
  'aplicaciones_tratamientos.update': {
    methods: ["PUT"],
    pattern: '/aplicaciones_tratamientos/:id',
    tokens: [{"old":"/aplicaciones_tratamientos/:id","type":0,"val":"aplicaciones_tratamientos","end":""},{"old":"/aplicaciones_tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['aplicaciones_tratamientos.update']['types'],
  },
  'aplicaciones_tratamientos.destroy': {
    methods: ["DELETE"],
    pattern: '/aplicaciones_tratamientos/:id',
    tokens: [{"old":"/aplicaciones_tratamientos/:id","type":0,"val":"aplicaciones_tratamientos","end":""},{"old":"/aplicaciones_tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['aplicaciones_tratamientos.destroy']['types'],
  },
  'imagenes.update': {
    methods: ["PUT"],
    pattern: '/imagenes/:id',
    tokens: [{"old":"/imagenes/:id","type":0,"val":"imagenes","end":""},{"old":"/imagenes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['imagenes.update']['types'],
  },
  'imagenes.destroy': {
    methods: ["DELETE"],
    pattern: '/imagenes/:id',
    tokens: [{"old":"/imagenes/:id","type":0,"val":"imagenes","end":""},{"old":"/imagenes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['imagenes.destroy']['types'],
  },
  'insumos.store': {
    methods: ["POST"],
    pattern: '/insumos',
    tokens: [{"old":"/insumos","type":0,"val":"insumos","end":""}],
    types: placeholder as Registry['insumos.store']['types'],
  },
  'insumos.update': {
    methods: ["PUT"],
    pattern: '/insumos/:id',
    tokens: [{"old":"/insumos/:id","type":0,"val":"insumos","end":""},{"old":"/insumos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['insumos.update']['types'],
  },
  'insumos.destroy': {
    methods: ["DELETE"],
    pattern: '/insumos/:id',
    tokens: [{"old":"/insumos/:id","type":0,"val":"insumos","end":""},{"old":"/insumos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['insumos.destroy']['types'],
  },
  'cat_tipos_insumos.store': {
    methods: ["POST"],
    pattern: '/cat_tipos_insumos',
    tokens: [{"old":"/cat_tipos_insumos","type":0,"val":"cat_tipos_insumos","end":""}],
    types: placeholder as Registry['cat_tipos_insumos.store']['types'],
  },
  'cat_tipos_insumos.update': {
    methods: ["PUT"],
    pattern: '/cat_tipos_insumos/:id',
    tokens: [{"old":"/cat_tipos_insumos/:id","type":0,"val":"cat_tipos_insumos","end":""},{"old":"/cat_tipos_insumos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_insumos.update']['types'],
  },
  'cat_tipos_insumos.destroy': {
    methods: ["DELETE"],
    pattern: '/cat_tipos_insumos/:id',
    tokens: [{"old":"/cat_tipos_insumos/:id","type":0,"val":"cat_tipos_insumos","end":""},{"old":"/cat_tipos_insumos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cat_tipos_insumos.destroy']['types'],
  },
  'cafeteros.store': {
    methods: ["POST"],
    pattern: '/cafeteros',
    tokens: [{"old":"/cafeteros","type":0,"val":"cafeteros","end":""}],
    types: placeholder as Registry['cafeteros.store']['types'],
  },
  'cafeteros.update': {
    methods: ["PUT"],
    pattern: '/cafeteros/:id',
    tokens: [{"old":"/cafeteros/:id","type":0,"val":"cafeteros","end":""},{"old":"/cafeteros/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cafeteros.update']['types'],
  },
  'cafeteros.destroy': {
    methods: ["DELETE"],
    pattern: '/cafeteros/:id',
    tokens: [{"old":"/cafeteros/:id","type":0,"val":"cafeteros","end":""},{"old":"/cafeteros/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cafeteros.destroy']['types'],
  },
  'fincas.index': {
    methods: ["GET","HEAD"],
    pattern: '/fincas',
    tokens: [{"old":"/fincas","type":0,"val":"fincas","end":""}],
    types: placeholder as Registry['fincas.index']['types'],
  },
  'fincas.store': {
    methods: ["POST"],
    pattern: '/fincas',
    tokens: [{"old":"/fincas","type":0,"val":"fincas","end":""}],
    types: placeholder as Registry['fincas.store']['types'],
  },
  'fincas.show': {
    methods: ["GET","HEAD"],
    pattern: '/fincas/:id',
    tokens: [{"old":"/fincas/:id","type":0,"val":"fincas","end":""},{"old":"/fincas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['fincas.show']['types'],
  },
  'fincas.update': {
    methods: ["PUT"],
    pattern: '/fincas/:id',
    tokens: [{"old":"/fincas/:id","type":0,"val":"fincas","end":""},{"old":"/fincas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['fincas.update']['types'],
  },
  'fincas.destroy': {
    methods: ["DELETE"],
    pattern: '/fincas/:id',
    tokens: [{"old":"/fincas/:id","type":0,"val":"fincas","end":""},{"old":"/fincas/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['fincas.destroy']['types'],
  },
  'fincas.upload_photo': {
    methods: ["POST"],
    pattern: '/fincas/:id/foto',
    tokens: [{"old":"/fincas/:id/foto","type":0,"val":"fincas","end":""},{"old":"/fincas/:id/foto","type":1,"val":"id","end":""},{"old":"/fincas/:id/foto","type":0,"val":"foto","end":""}],
    types: placeholder as Registry['fincas.upload_photo']['types'],
  },
  'cultivos.index': {
    methods: ["GET","HEAD"],
    pattern: '/cultivos',
    tokens: [{"old":"/cultivos","type":0,"val":"cultivos","end":""}],
    types: placeholder as Registry['cultivos.index']['types'],
  },
  'cultivos.store': {
    methods: ["POST"],
    pattern: '/cultivos',
    tokens: [{"old":"/cultivos","type":0,"val":"cultivos","end":""}],
    types: placeholder as Registry['cultivos.store']['types'],
  },
  'cultivos.show': {
    methods: ["GET","HEAD"],
    pattern: '/cultivos/:id',
    tokens: [{"old":"/cultivos/:id","type":0,"val":"cultivos","end":""},{"old":"/cultivos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cultivos.show']['types'],
  },
  'cultivos.update': {
    methods: ["PUT"],
    pattern: '/cultivos/:id',
    tokens: [{"old":"/cultivos/:id","type":0,"val":"cultivos","end":""},{"old":"/cultivos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cultivos.update']['types'],
  },
  'cultivos.destroy': {
    methods: ["DELETE"],
    pattern: '/cultivos/:id',
    tokens: [{"old":"/cultivos/:id","type":0,"val":"cultivos","end":""},{"old":"/cultivos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cultivos.destroy']['types'],
  },
  'cultivos.upload_photo': {
    methods: ["POST"],
    pattern: '/cultivos/:id/foto',
    tokens: [{"old":"/cultivos/:id/foto","type":0,"val":"cultivos","end":""},{"old":"/cultivos/:id/foto","type":1,"val":"id","end":""},{"old":"/cultivos/:id/foto","type":0,"val":"foto","end":""}],
    types: placeholder as Registry['cultivos.upload_photo']['types'],
  },
  'monitoreos.index': {
    methods: ["GET","HEAD"],
    pattern: '/monitoreos',
    tokens: [{"old":"/monitoreos","type":0,"val":"monitoreos","end":""}],
    types: placeholder as Registry['monitoreos.index']['types'],
  },
  'monitoreos.show': {
    methods: ["GET","HEAD"],
    pattern: '/monitoreos/:id',
    tokens: [{"old":"/monitoreos/:id","type":0,"val":"monitoreos","end":""},{"old":"/monitoreos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['monitoreos.show']['types'],
  },
  'monitoreos.store': {
    methods: ["POST"],
    pattern: '/monitoreos',
    tokens: [{"old":"/monitoreos","type":0,"val":"monitoreos","end":""}],
    types: placeholder as Registry['monitoreos.store']['types'],
  },
  'monitoreos.destroy': {
    methods: ["DELETE"],
    pattern: '/monitoreos/:id',
    tokens: [{"old":"/monitoreos/:id","type":0,"val":"monitoreos","end":""},{"old":"/monitoreos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['monitoreos.destroy']['types'],
  },
  'analisis_ia.index': {
    methods: ["GET","HEAD"],
    pattern: '/analisis_ia',
    tokens: [{"old":"/analisis_ia","type":0,"val":"analisis_ia","end":""}],
    types: placeholder as Registry['analisis_ia.index']['types'],
  },
  'analisis_ia.show': {
    methods: ["GET","HEAD"],
    pattern: '/analisis_ia/:id',
    tokens: [{"old":"/analisis_ia/:id","type":0,"val":"analisis_ia","end":""},{"old":"/analisis_ia/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['analisis_ia.show']['types'],
  },
  'analisis_ia.store': {
    methods: ["POST"],
    pattern: '/analisis_ia',
    tokens: [{"old":"/analisis_ia","type":0,"val":"analisis_ia","end":""}],
    types: placeholder as Registry['analisis_ia.store']['types'],
  },
  'recomendaciones.index': {
    methods: ["GET","HEAD"],
    pattern: '/recomendaciones',
    tokens: [{"old":"/recomendaciones","type":0,"val":"recomendaciones","end":""}],
    types: placeholder as Registry['recomendaciones.index']['types'],
  },
  'recomendaciones.show': {
    methods: ["GET","HEAD"],
    pattern: '/recomendaciones/:id',
    tokens: [{"old":"/recomendaciones/:id","type":0,"val":"recomendaciones","end":""},{"old":"/recomendaciones/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['recomendaciones.show']['types'],
  },
  'tratamientos.index': {
    methods: ["GET","HEAD"],
    pattern: '/tratamientos',
    tokens: [{"old":"/tratamientos","type":0,"val":"tratamientos","end":""}],
    types: placeholder as Registry['tratamientos.index']['types'],
  },
  'tratamientos.show': {
    methods: ["GET","HEAD"],
    pattern: '/tratamientos/:id',
    tokens: [{"old":"/tratamientos/:id","type":0,"val":"tratamientos","end":""},{"old":"/tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tratamientos.show']['types'],
  },
  'aplicaciones_tratamientos.index': {
    methods: ["GET","HEAD"],
    pattern: '/aplicaciones_tratamientos',
    tokens: [{"old":"/aplicaciones_tratamientos","type":0,"val":"aplicaciones_tratamientos","end":""}],
    types: placeholder as Registry['aplicaciones_tratamientos.index']['types'],
  },
  'aplicaciones_tratamientos.show': {
    methods: ["GET","HEAD"],
    pattern: '/aplicaciones_tratamientos/:id',
    tokens: [{"old":"/aplicaciones_tratamientos/:id","type":0,"val":"aplicaciones_tratamientos","end":""},{"old":"/aplicaciones_tratamientos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['aplicaciones_tratamientos.show']['types'],
  },
  'imagenes.index': {
    methods: ["GET","HEAD"],
    pattern: '/imagenes',
    tokens: [{"old":"/imagenes","type":0,"val":"imagenes","end":""}],
    types: placeholder as Registry['imagenes.index']['types'],
  },
  'imagenes.show': {
    methods: ["GET","HEAD"],
    pattern: '/imagenes/:id',
    tokens: [{"old":"/imagenes/:id","type":0,"val":"imagenes","end":""},{"old":"/imagenes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['imagenes.show']['types'],
  },
  'imagenes.store': {
    methods: ["POST"],
    pattern: '/imagenes',
    tokens: [{"old":"/imagenes","type":0,"val":"imagenes","end":""}],
    types: placeholder as Registry['imagenes.store']['types'],
  },
  'experto.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/experto/dashboard',
    tokens: [{"old":"/experto/dashboard","type":0,"val":"experto","end":""},{"old":"/experto/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['experto.dashboard']['types'],
  },
  'experto.fincas': {
    methods: ["GET","HEAD"],
    pattern: '/experto/fincas',
    tokens: [{"old":"/experto/fincas","type":0,"val":"experto","end":""},{"old":"/experto/fincas","type":0,"val":"fincas","end":""}],
    types: placeholder as Registry['experto.fincas']['types'],
  },
  'experto.cultivos': {
    methods: ["GET","HEAD"],
    pattern: '/experto/cultivos',
    tokens: [{"old":"/experto/cultivos","type":0,"val":"experto","end":""},{"old":"/experto/cultivos","type":0,"val":"cultivos","end":""}],
    types: placeholder as Registry['experto.cultivos']['types'],
  },
  'experto.monitoreos': {
    methods: ["GET","HEAD"],
    pattern: '/experto/monitoreos',
    tokens: [{"old":"/experto/monitoreos","type":0,"val":"experto","end":""},{"old":"/experto/monitoreos","type":0,"val":"monitoreos","end":""}],
    types: placeholder as Registry['experto.monitoreos']['types'],
  },
  'experto.analisis_ia': {
    methods: ["GET","HEAD"],
    pattern: '/experto/analisis_ia',
    tokens: [{"old":"/experto/analisis_ia","type":0,"val":"experto","end":""},{"old":"/experto/analisis_ia","type":0,"val":"analisis_ia","end":""}],
    types: placeholder as Registry['experto.analisis_ia']['types'],
  },
  'experto.crear_monitoreo': {
    methods: ["POST"],
    pattern: '/experto/monitoreos',
    tokens: [{"old":"/experto/monitoreos","type":0,"val":"experto","end":""},{"old":"/experto/monitoreos","type":0,"val":"monitoreos","end":""}],
    types: placeholder as Registry['experto.crear_monitoreo']['types'],
  },
  'experto.actualizar_monitoreo': {
    methods: ["PUT"],
    pattern: '/experto/monitoreos/:id',
    tokens: [{"old":"/experto/monitoreos/:id","type":0,"val":"experto","end":""},{"old":"/experto/monitoreos/:id","type":0,"val":"monitoreos","end":""},{"old":"/experto/monitoreos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['experto.actualizar_monitoreo']['types'],
  },
  'experto.recomendaciones': {
    methods: ["GET","HEAD"],
    pattern: '/experto/recomendaciones',
    tokens: [{"old":"/experto/recomendaciones","type":0,"val":"experto","end":""},{"old":"/experto/recomendaciones","type":0,"val":"recomendaciones","end":""}],
    types: placeholder as Registry['experto.recomendaciones']['types'],
  },
  'experto.crear_recomendacion': {
    methods: ["POST"],
    pattern: '/experto/recomendaciones',
    tokens: [{"old":"/experto/recomendaciones","type":0,"val":"experto","end":""},{"old":"/experto/recomendaciones","type":0,"val":"recomendaciones","end":""}],
    types: placeholder as Registry['experto.crear_recomendacion']['types'],
  },
  'experto.actualizar_recomendacion': {
    methods: ["PUT"],
    pattern: '/experto/recomendaciones/:id',
    tokens: [{"old":"/experto/recomendaciones/:id","type":0,"val":"experto","end":""},{"old":"/experto/recomendaciones/:id","type":0,"val":"recomendaciones","end":""},{"old":"/experto/recomendaciones/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['experto.actualizar_recomendacion']['types'],
  },
  'experto.tratamientos': {
    methods: ["GET","HEAD"],
    pattern: '/experto/tratamientos',
    tokens: [{"old":"/experto/tratamientos","type":0,"val":"experto","end":""},{"old":"/experto/tratamientos","type":0,"val":"tratamientos","end":""}],
    types: placeholder as Registry['experto.tratamientos']['types'],
  },
  'experto.aplicaciones_tratamiento': {
    methods: ["GET","HEAD"],
    pattern: '/experto/aplicaciones_tratamiento',
    tokens: [{"old":"/experto/aplicaciones_tratamiento","type":0,"val":"experto","end":""},{"old":"/experto/aplicaciones_tratamiento","type":0,"val":"aplicaciones_tratamiento","end":""}],
    types: placeholder as Registry['experto.aplicaciones_tratamiento']['types'],
  },
  'experto.crear_aplicacion_tratamiento': {
    methods: ["POST"],
    pattern: '/experto/aplicaciones_tratamiento',
    tokens: [{"old":"/experto/aplicaciones_tratamiento","type":0,"val":"experto","end":""},{"old":"/experto/aplicaciones_tratamiento","type":0,"val":"aplicaciones_tratamiento","end":""}],
    types: placeholder as Registry['experto.crear_aplicacion_tratamiento']['types'],
  },
  'caficultor.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/caficultor/dashboard',
    tokens: [{"old":"/caficultor/dashboard","type":0,"val":"caficultor","end":""},{"old":"/caficultor/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['caficultor.dashboard']['types'],
  },
  'caficultor.fincas': {
    methods: ["GET","HEAD"],
    pattern: '/caficultor/fincas',
    tokens: [{"old":"/caficultor/fincas","type":0,"val":"caficultor","end":""},{"old":"/caficultor/fincas","type":0,"val":"fincas","end":""}],
    types: placeholder as Registry['caficultor.fincas']['types'],
  },
  'caficultor.cultivos': {
    methods: ["GET","HEAD"],
    pattern: '/caficultor/cultivos',
    tokens: [{"old":"/caficultor/cultivos","type":0,"val":"caficultor","end":""},{"old":"/caficultor/cultivos","type":0,"val":"cultivos","end":""}],
    types: placeholder as Registry['caficultor.cultivos']['types'],
  },
  'caficultor.monitoreos': {
    methods: ["GET","HEAD"],
    pattern: '/caficultor/monitoreos',
    tokens: [{"old":"/caficultor/monitoreos","type":0,"val":"caficultor","end":""},{"old":"/caficultor/monitoreos","type":0,"val":"monitoreos","end":""}],
    types: placeholder as Registry['caficultor.monitoreos']['types'],
  },
  'caficultor.recomendaciones': {
    methods: ["GET","HEAD"],
    pattern: '/caficultor/recomendaciones',
    tokens: [{"old":"/caficultor/recomendaciones","type":0,"val":"caficultor","end":""},{"old":"/caficultor/recomendaciones","type":0,"val":"recomendaciones","end":""}],
    types: placeholder as Registry['caficultor.recomendaciones']['types'],
  },
  'caficultor.analisis_ia': {
    methods: ["GET","HEAD"],
    pattern: '/caficultor/analisis_ia',
    tokens: [{"old":"/caficultor/analisis_ia","type":0,"val":"caficultor","end":""},{"old":"/caficultor/analisis_ia","type":0,"val":"analisis_ia","end":""}],
    types: placeholder as Registry['caficultor.analisis_ia']['types'],
  },
  'caficultor.expertos_asignados': {
    methods: ["GET","HEAD"],
    pattern: '/caficultor/expertos_asignados',
    tokens: [{"old":"/caficultor/expertos_asignados","type":0,"val":"caficultor","end":""},{"old":"/caficultor/expertos_asignados","type":0,"val":"expertos_asignados","end":""}],
    types: placeholder as Registry['caficultor.expertos_asignados']['types'],
  },
  'caficultor.analizar_imagen': {
    methods: ["POST"],
    pattern: '/caficultor/analizar-imagen',
    tokens: [{"old":"/caficultor/analizar-imagen","type":0,"val":"caficultor","end":""},{"old":"/caficultor/analizar-imagen","type":0,"val":"analizar-imagen","end":""}],
    types: placeholder as Registry['caficultor.analizar_imagen']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
